### ISSUE TITLE
fix naming

### ISSUE THREAD

**Issue by till** [easybiblabs/bib-vagrant#9]
I think we should do this:

```
test-vagrant
`-- lib
    |-- bib-vagrant
    |   |-- config.rb
    |   |-- plugin.rb
    |   `-- version.rb
    `-- bib-vagrant.rb

2 directories, 4 files
```

This is more along the way how other plugins are written/organized.

**Comment by gilleyj** [comment]
@till, @fh, funny about this, the bundle ruby building process does the bib/vagrant split automagically.  This was a big source of my confusion when I was learning how to add my provisioner.  Also the provisioner.rb filename is generic, and would require filename refactoring if a new provisioner wanted to be added.   (my bad)
